#!/system/bin/sh
# 
# Mount fonts partition
#

mount -w -o remount /system
mkdir /system/fonts 
chown -R 1000.1000 /system/fonts 
chmod -R 777 /system/fonts 
mount -t yaffs2 /dev/block/mtdblock7 /system/fonts
chown -R 1000.1000 /system/fonts 
chmod -R 777 /system/fonts

mkdir /system/media
chown -R 1000.1000 /system/media
chmod -R 777 /system/media
mount -t yaffs2 /dev/block/mtdblock8 /system/media
chown -R 1000.1000 /system/media
chmod -R 777 /system/media

mkdir /system/tts
chown -R 1000.1000 /system/tts
chmod -R 777 /system/tts
mount -t yaffs2 /dev/block/mtdblock8 /system/tts
chown -R 1000.1000 /system/tts
chmod -R 777 /system/tts
