#!/system/bin/sh

# Activate swap
if [ "$(cat /proc/partitions | grep mmcblk0p3)" != "" ]; then
	swapon /dev/block/mmcblk0p3
fi

# Activate compcache (using new sysctl method; not supported officially by CyanogenMod?)
if getprop | grep persist.service.compcache; then
	COMPCACHE=`getprop persist.service.compcache`
else
	COMPCACHE=`getprop ro.compcache.default`
fi

if [ "$COMPCACHE" -ne "0" ]; then
	COMPCACHERAM=$((184 * $COMPCACHE / 100))
	insmod /system/lib/modules/zram.ko
	echo 1 > /sys/block/zram0/reset
	echo $(($COMPCACHERAM*1024*1024)) > /sys/block/zram0/disksize
	mkswap /dev/block/zram0
	swapon /dev/block/zram0
fi

#patch simple2ext's script to prevent filesystem corruption
S2ECONFIG="/data/local/s2e_config/.mounts_ext4"
if [ -f $S2ECONFIG ];
then
	# remove dangerous tune2fs tweaks
	sed -i -e 's/ tune2fs -/ #tune2fs -/g' -e 's/ e2fsck/ #e2fsck/g' \
	-e 's/-o commit=19,barrier=0,nobh,nouser_xattr,errors=continue,noatime,nodiratime,nosuid,nodev,data=writeback//g' $S2ECONFIG
fi

#check softmac
if [ -e /system/wifi/softmac ];
then
        cp /system/wifi/softmac /data/misc/wifi/softmac;
        sync
fi

# mount ext partition from sd card

BB="logwrapper busybox";

if [ "$SD_EXT_DIRECTORY" = "" ];
then
    SD_EXT_DIRECTORY=/sd-ext;
fi;

# find SD Card
for MMC_NUM in `seq 0 9`;
do
    MMC_TYPE=`cat /sys/block/mmcblk$MMC_NUM/device/type`
    if [ "$MMC_TYPE" = "SD" ];
    then
        # 2nd partition of sdcard should be the sd-ext if exist
        SD_EXT_PART=/dev/block/mmcblk${MMC_NUM}p2
        break
    fi
done

if [ -b "$SD_EXT_PART" ];
then
    log -p i -t mountsd "Checking filesystems..";

    # fsck the sdcard filesystem first
    if [ -x `which e2fsck` ];
    then
        e2fsck -y $SD_EXT_PART
        e2fsk_exitcode=$?
    else
        echo "executable e2fsck not found, assuming no filesystem errors"
        e2fsk_exitcode=0
    fi

    # set property with exit code in case an error occurs
    setprop cm.e2fsck.errors $e2fsk_exitcode;
    if [ "$e2fsk_exitcode" -lt 2 ];
    then
        # mount and set perms
        $BB mount -o noatime,nodiratime,barrier=1 -t ext4 $SD_EXT_PART $SD_EXT_DIRECTORY;
        if [ "$?" = 0 ];
        then
            $BB chown 1000:1000 $SD_EXT_DIRECTORY;
            $BB chmod 771 $SD_EXT_DIRECTORY;
            log -p i -t mountsd "$SD_EXT_DIRECTORY successfully mounted";
        else
            log -p e -t mountsd "Unable to mount filesystem for $SD_EXT_DIRECTORY!";
        fi
    else
        log -p e -t mountsd "Unable to repair filesystem, disabling apps2sd";
    fi
fi

